const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Adidas Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 150,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Puma Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 190,
      countInStock: 0,
      brand: 'Puma',
      rating: 4.6,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Dell Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 140,
      countInStock: 10,
      brand: 'Dell',
      rating: 5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'HP Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 150,
      countInStock: 10,
      brand: 'HP',
      rating: 4.2,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Asus Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 100,
      brand: 'Asus',
      rating: 3.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};

export default data;
